### PR TITLE
Fix flag connected

### PR DESCRIPTION
**Pull request by fernando-goncalves-movile**
- change flag connect to true when the connection is opened, also valid for reconnection now
- abort the flow of send message if the flag is off
- minor changes

### CODE REVIEW

**Comment by fernando-goncalves-movile** [comment]
I still have to test the change.

**Comment by fernando-goncalves-movile** [comment]
Tests OK

**Comment by diego-rocha-movile** [comment]
LGTM

**Comment by rodrigo-marchesini-movile** [comment]
Ship it.

**Pull request merged**
